apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    namespace: default
    name: spring-roles
rules:
-   apiGroups: [""]
    resources: ["pods","configmaps"]
    verbs: ["list","get","watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: allow-sping-to-cluster
subjects:
-   kind: ServiceAccount
    name: default
    namespace: default
roleRef:
    kind: ClusterRole
    name: spring-roles
    apiGroup: rbac.authorization.k8s.io
